version: '3.8'
services:
  movies:
    image: jagadeeshijjada/movies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
  metro:
    image: jagadeeshijjada/metro:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3
  dth:
    image: jagadeeshijjada/dth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
  recharge:
    image: jagadeeshijjada/recharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
